# https://devdocs.prestashop.com/8/modules/concepts/services/
services:
  PrestaShop\Module\DemoExtendTemplates\Controller\DecoratedOrderController:
    class: PrestaShop\Module\DemoExtendTemplates\Controller\DecoratedOrderController
    decorates: PrestaShopBundle\Controller\Admin\Sell\Order\OrderController
    arguments: ['@PrestaShop\Module\DemoExtendTemplates\Controller\DecoratedOrderController.inner']

